In [84]:
import numpy as np
from datetime import datetime
start_time = datetime.now()

In [85]:
def jacobi(A, b, tolerance=1e-3, max_iterations=10000):
    
    x = np.zeros_like(b, dtype=np.float)
    #A=np.array((A),dtype=float)
    #b=np.array((b),dtype=float)
    
    T = A - np.diag(np.diagonal(A))
    
    if checkDiagnolDominant(a) == False:
           return False
    
    for k in range(max_iterations):
        
        x_old  = x.copy()
        
        x[:] = (b - np.dot(T, x)) / np.diagonal(A)
        
       
        
        if np.linalg.norm(x - x_old, ord=np.inf) / np.linalg.norm(x, ord=np.inf) < tolerance:
            break
        print(x)    
    return x

In [86]:
def checkDiagnolDominant(a):
    # Find diagonal coefficients
    diag = np.diag(np.abs(a)) 

    # Find row sum without diagonal
    off_diag = np.sum(np.abs(a), axis=1) - diag 

    if np.all(diag > off_diag):
        print('matrix is diagonally dominant')
        return True
    else:
        print('NOT diagonally dominant')
        return False

In [89]:
x = [0, 0, 0]                        
a = np.array([[8.0011, 7.9511, 7.0011],[1.1199,5.1471,9.8974],[9.1251,0.1514,8.9898]])
b = np.array([1,9,1])
#a = np.array([[8,5,2],[5,8,2],[2,5,8]])
#b = np.array([8,5,2])


print("Input matrix : ",a)
print("freq:", b)
print("======")
#make existing diagnolly dominant : only use when using random generator and not static matrix
#for i in range(a.shape[0]):
#    d = a[i][i]
#    a[i][i] = sum(a[i]) - d + 1
print("Input matrix : ",a)
print("freq:", b)
print("======")    
jacobi(a,b)
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

Input matrix :  [[8.0011 7.9511 7.0011]
 [1.1199 5.1471 9.8974]
 [9.1251 0.1514 8.9898]]
freq: [1 9 1]
Input matrix :  [[8.0011 7.9511 7.0011]
 [1.1199 5.1471 9.8974]
 [9.1251 0.1514 8.9898]]
freq: [1 9 1]
NOT diagonally dominant
Duration: 0:01:22.030686
